[build]
  # 构建命令（静态网站不需要构建）
  command = "echo '静态网站，无需构建'"
  
  # 发布目录
  publish = "."

[build.environment]
  # Node.js版本（如果需要的话）
  NODE_VERSION = "18"

# 重定向规则 - 确保SPA正常工作
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# 头部设置 - 缓存优化和防缓存策略
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    Last-Modified = "Fri, 17 Jan 2025 00:00:00 GMT"
    ETag = "v1.3.0"

# 表单处理（如果需要的话）
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

# 环境变量（如果需要的话）
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
